# Generated by Django 5.0.4 on 2024-05-02 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
