# Generated by Django 5.0.4 on 2024-05-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_group_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('des', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='images/recipe')),
            ],
        ),
    ]
