# Generated by Django 5.0.4 on 2024-05-15 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('education_12th_percentage', models.FloatField()),
                ('ug_percentage', models.FloatField()),
                ('resume', models.FileField(upload_to='images/job')),
                ('photo', models.ImageField(upload_to='images/job')),
                ('certifications', models.TextField()),
                ('skills', models.TextField()),
                ('linkedin_url', models.URLField()),
                ('github_url', models.URLField()),
                ('leetcode_url', models.URLField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.job')),
            ],
        ),
    ]
