# Generated by Django 5.0.4 on 2024-05-20 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_alter_careerregister_password1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
