# Generated by Django 5.0.4 on 2024-04-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_id', models.IntegerField()),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Emp_age', models.IntegerField()),
                ('Emp_Role', models.CharField(max_length=50)),
                ('Emp_city', models.CharField(max_length=50)),
                ('Emp_salary', models.IntegerField()),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Rdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password1', models.IntegerField()),
                ('password12', models.IntegerField()),
                ('login', models.CharField(max_length=50)),
            ],
        ),
    ]
