# Generated by Django 5.0.4 on 2024-04-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_Emp', '0003_todo_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='images/profile')),
                ('summary', models.TextField()),
                ('company_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('start_date', models.CharField(max_length=100)),
                ('end_date', models.CharField(max_length=100)),
                ('twelfth_degree', models.CharField(max_length=100)),
                ('twelfth_passout', models.CharField(max_length=50)),
                ('twelfth_percentage', models.CharField(max_length=10)),
                ('bachelor_degree', models.CharField(max_length=100)),
                ('bachelor_passout', models.CharField(max_length=50)),
                ('bachelor_percentage', models.CharField(max_length=10)),
                ('salary', models.IntegerField()),
                ('joining_date', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('bio', models.TextField()),
            ],
            options={
                'db_table': 'profile_data',
            },
        ),
    ]
