# Generated by Django 5.0.4 on 2024-05-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_Emp', '0025_job_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password1', models.CharField(max_length=50)),
                ('password2', models.CharField(max_length=50)),
            ],
        ),
    ]
