# Generated by Django 5.0.4 on 2024-05-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_Emp', '0026_careerregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerregister',
            name='password1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='careerregister',
            name='password2',
            field=models.IntegerField(),
        ),
    ]
